ADD_SQL = "insert into students(id, code, first_name, last_name, birthOfDate, math, physics, chemistry) values (%s,%s,%s,%s,%s,%s,%s,%s)"
UPDATE_SQL = "update students set first_name = %s, last_name = %s, birthOfDate = %s, math = %s, physics = %s, chemistry = %s where id = %s"
DELETE_SQL = "delete from students where id = %s"
GET_STUDENT_SQL = "select * from students where id = %s"
SHOW_LIST_SQL = "select * from students"